wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.28
    is_jupyter_run: true
    python_version: 3.7.5
batch_size:
  desc: null
  value: 8
steps_per_epoch:
  desc: null
  value: 1000
